### ISSUE TITLE
Pressing 'q' doesn't terminate

### ISSUE THREAD

**Issue by martinezgjuan** [Mimino666/tc-marathoner#1]
Pressing 'q' doesn't terminate the execution with neither single or multiple cases.

I'm using:
Windows 7.
Java 1.8.0_45
Python 3.4.3.

**Comment by Mimino666** [comment]
Nice catch! 
It was an issue on Python 3.x versions on Windows. Should be fixed now.
Run: `pip install marathoner --upgrade` and let me know if it works.

**Comment by martinezgjuan** [comment]
Working well now =)
