### ISSUE TITLE
Update for new Marathon Match

### ISSUE THREAD

**Issue by CatalinTiseanu** [Mimino666/tc-marathoner#3]
Would it be possible to update Marathoner for the PopulationMapping TopCoder Marathon match ?

**Comment by Mimino666** [comment]
Update to v1.2.17. It should work now (4f261e33a4e24acf25e1307ed89770f6ba235309).
Please let me know if there is a problem.

And thank you for pinging me about it :)

**Comment by CatalinTiseanu** [comment]
Thanks for getting back so quickly ! :)

I think there is a communication issue between the visualizer and solution since in this problem the viz listens continuously for questions from the solution (population queries for a rectangle).

For me it hangs as soon as my solution asks a question.

**Comment by Mimino666** [comment]
I believe I solved it in v1.2.17. Or is it still a problem?

**Comment by CatalinTiseanu** [comment]
Yeah, I updated to v.1.217 and the solution hangs while waiting for the visualizer's response to the first question.

**Comment by Mimino666** [comment]
Also make sure that you named your marathoner project _PopulationMappingMarat_. Through that the marathoner recognizes the marathon match and uses the correct way to communicate with visualizer.

**Comment by CatalinTiseanu** [comment]
I have my marathoner.cfg in PopulationMappingMarat/

I hope I'm not missing something obvious.

**Comment by Mimino666** [comment]
Try to delete the PopulationMappingMarat/cache/ directory. If this won't help, I will have to dig further.

**Comment by CatalinTiseanu** [comment]
It didn't work :( Does it work on your end for PopulationMapping ?

**Comment by CatalinTiseanu** [comment]
Hello again ! :)

Unfortunately I didn't have time for PopulationMapping so I didn't continue digging with marathoner.
However, it still doesn't work for me for the new match, ViralInfection.

It hangs waiting for stdin just after outputting the first Research.addmed query.
I'm on OS X.
I was wondering if the fix for PopulationMapping worked for other people.

I can fix it myself if you could point me to the place in the code where the communication between the solution and the visualizer takes place.

**Comment by Mimino666** [comment]
I will prepare Marathoner for the new match during today. I will ping you, when it's ready.

**Comment by Mimino666** [comment]
I have updated Marathoner. Give it a try and let me know if there are any problems.

**Comment by CatalinTiseanu** [comment]
Hi Mimino,

It works like a charm ! :)
Thank you for your invaluable tool !

Catalin
